name: Code Check (SPDX ID and Copyright)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install PHP
        run: sudo apt-get install php -y;

      - name: Do check
        run: |
          php code_check.php codewars;
