name: Code Check (SPDX ID and Copyright)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install PHP
        run: sudo apt-get install php -y;

      - name: Do check
        run: |
          php code_check.php codewars;

      - name: Update Codewars Stats
        uses: stefanzweifel/git-auto-commit-action@v4.11.0
        with:
          commit_message: |
            README.md: update Codewars stats

            Co-authored-by: GitHub Support <support@github.com>

          branch: main
          commit_options: '--no-verify --signoff'
          file_pattern: README.md
          repository: .
          push_options: '--force'
          skip_dirty_check: true
          skip_fetch: false
          disable_globbing: true
