name: Check SPDX ID and Update Stats

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install PHP
        run: sudo apt-get install php -y;

      - name: Do check
        run: |
          php code_check.php codewars;

      - name: Generate codewars stats
        run: |
          php genstats.php codewars;

      - name: Commit and push changes
        shell: bash
        if: github.event_name != 'pull_request'
        run: |
          git config --global user.name "GitHub Actions" && \
          git config --global user.email "actions@github.com" && \
          git add -A && \
          git commit -s -m "$(echo -e 'README.md: update codewars stats\n\nCo-authored-by: GitHub Staff <support@github.com>\nSigned-off-by: GitHub Actions <actions@github.com>')" && \
          git push -vf origin ${GITHUB_REF##*/};
